/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stats.exam.assist;

import org.apache.commons.math3.util.CombinatoricsUtils;

/**
 *
 * @author Michael
 */
public class HyperGeomForm extends javax.swing.JFrame {

    /**
     * Creates new form HyperGeomForm
     */
    public HyperGeomForm() {
        initComponents();
    }
    
    private double calculateCombination(int n, int r){
        double nFactorial = CombinatoricsUtils.factorialDouble(n);
        double nMinusRfactorial = CombinatoricsUtils.factorialDouble(n-r);
        double rFactorial = CombinatoricsUtils.factorial(r);
        return nFactorial / (rFactorial * nMinusRfactorial);
    }

    private double calculateHyperGeometric(double firstTerm, double secondterm, double thirdTerm){
        return (firstTerm * secondterm) / thirdTerm;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variableContainer = new javax.swing.JPanel();
        NLabel = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        NValue = new javax.swing.JFormattedTextField();
        nValue = new javax.swing.JFormattedTextField();
        rValue = new javax.swing.JFormattedTextField();
        yValue = new javax.swing.JFormattedTextField();
        descriptionLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        resultContainer = new javax.swing.JPanel();
        resultField = new javax.swing.JFormattedTextField();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        variableContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables"));

        NLabel.setText("N");

        nLabel.setText("n");

        rLabel.setText("r");

        yLabel.setText("y");

        NValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        nValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        yValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        descriptionLabel.setText("jLabel1");
        descriptionLabel.setText("<html><i>N</i> is the total"
            + " number of elements<br />"
            + "<i>n</i> is the number of elements drawn<br />"
            + "<i>r</i> is the number of S's in the <i>N</i> "
            + "elements<br/>"
            + "<i>y</i> is the number of S's drawn in the <i>"
            + "n</i> elements</html>");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout variableContainerLayout = new javax.swing.GroupLayout(variableContainer);
        variableContainer.setLayout(variableContainerLayout);
        variableContainerLayout.setHorizontalGroup(
            variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variableContainerLayout.createSequentialGroup()
                .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(variableContainerLayout.createSequentialGroup()
                        .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(variableContainerLayout.createSequentialGroup()
                                .addComponent(NLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NValue, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addGroup(variableContainerLayout.createSequentialGroup()
                                .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nLabel)
                                    .addComponent(rLabel)
                                    .addComponent(yLabel))
                                .addGap(11, 11, 11)
                                .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yValue)
                                    .addComponent(nValue)
                                    .addComponent(rValue))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, variableContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calculateButton)))
                .addContainerGap())
        );
        variableContainerLayout.setVerticalGroup(
            variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variableContainerLayout.createSequentialGroup()
                .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(variableContainerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(variableContainerLayout.createSequentialGroup()
                        .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NLabel)
                            .addComponent(NValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nLabel)
                            .addComponent(nValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rLabel)
                            .addComponent(rValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(variableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yLabel)
                            .addComponent(yValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateButton)
                .addContainerGap())
        );

        getContentPane().add(variableContainer);

        resultContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        resultLabel.setText("Result:");

        javax.swing.GroupLayout resultContainerLayout = new javax.swing.GroupLayout(resultContainer);
        resultContainer.setLayout(resultContainerLayout);
        resultContainerLayout.setHorizontalGroup(
            resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultContainerLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        resultContainerLayout.setVerticalGroup(
            resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLabel))
                .addContainerGap())
        );

        getContentPane().add(resultContainer);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        //Take the text values and change them into ints
        int N =((Long)NValue.getValue()).intValue();
        int n = ((Long)nValue.getValue()).intValue();
        int r = ((Long)rValue.getValue()).intValue();
        int y = ((Long)yValue.getValue()).intValue();
        
        double ryCombination = calculateCombination(r, y);
        double nNCombination = calculateCombination(N, n);
        
        int nMinusR = N - r;
        int nMinusY = n - y;
        
        double bigCombo = calculateCombination(nMinusR, nMinusY);
        
        double geometric = calculateHyperGeometric(ryCombination, bigCombo, nNCombination);
        System.out.println("Hypergoemetric value: " + geometric);
        resultField.setValue(geometric);
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HyperGeomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HyperGeomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HyperGeomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HyperGeomForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HyperGeomForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NLabel;
    private javax.swing.JFormattedTextField NValue;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel nLabel;
    private javax.swing.JFormattedTextField nValue;
    private javax.swing.JLabel rLabel;
    private javax.swing.JFormattedTextField rValue;
    private javax.swing.JPanel resultContainer;
    private javax.swing.JFormattedTextField resultField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel variableContainer;
    private javax.swing.JLabel yLabel;
    private javax.swing.JFormattedTextField yValue;
    // End of variables declaration//GEN-END:variables
}
